### ISSUE TITLE
怎么不能注册

### ISSUE THREAD

**Issue by hoojking** [yuanguangxin/housing-transactions-fronted#33]
铁汁，怎么注册不了账号，登录不进去阿。急急急！！！！！！

**Comment by yuanguangxin** [comment]
可以详细描述一下你的问题




yuanguangxin
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuanguangxin/housing-transactions-fronted"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月24日(星期五) 下午5:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[yuanguangxin/housing-transactions-fronted] 怎么不能注册 (Issue #33)





 
铁汁，怎么注册不了账号，登录不进去阿。急急急！！！！！！

**Comment by hoojking** [comment]
你好 我只能运行出前端 但是没有数据
能说下你的代码逻辑吗或者需要配置哪些环境&nbsp; 我跑不起来你的项目
（我是个小菜鸡，但是看见你的展示图很漂亮&nbsp; 我想学学）
希望收到你的回复 谢谢了&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuanguangxin/housing-transactions-fronted"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuanguangxin/housing-transactions-fronted] 怎么不能注册 (Issue #33)





 可以详细描述一下你的问题 
 
 
 
 
 yuanguangxin 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "yuanguangxin/housing-transactions-fronted"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年2月24日(星期五) 下午5:49 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[yuanguangxin/housing-transactions-fronted] 怎么不能注册 (Issue #33) 
 
 
 
 
 
   
 铁汁，怎么注册不了账号，登录不进去阿。急急急！！！！！！

**Comment by yuanguangxin** [comment]
后端就是简单的Maven项目（记得要初始化db结构，在https://github.com/yuanguangxin/housing-transactions/blob/master/src/main/resources/init/housing_transactions.sql）。先启后端，保证后端先不报错。然后起前端，前端起来了之后要在前端代码里看看前端调后端的ip和端口是否正确（我这个代码后端默认80，前端也通过nginx转发到80了，如果没有nginx，改一下前端代码http调用的ip端口前缀即可）。




我知道金银花的别名
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuanguangxin/housing-transactions-fronted"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 中午12:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuanguangxin/housing-transactions-fronted] 怎么不能注册 (Issue #33)





 你好 我只能运行出前端 但是没有数据 
 能说下你的代码逻辑吗或者需要配置哪些环境&amp;nbsp; 我跑不起来你的项目 
 （我是个小菜鸡，但是看见你的展示图很漂亮&amp;nbsp; 我想学学） 
 希望收到你的回复 谢谢了&amp;nbsp; 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "yuanguangxin/housing-transactions-fronted"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月1日(星期三) 上午10:27 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [yuanguangxin/housing-transactions-fronted] 怎么不能注册 (Issue #33) 
 
 
 
 
 
  可以详细描述一下你的问题  
   
   
   
   
  yuanguangxin  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "yuanguangxin/housing-transactions-fronted"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年2月24日(星期五) 下午5:49  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[yuanguangxin/housing-transactions-fronted] 怎么不能注册 (Issue #33)  
   
   
   
   
   
     
  铁汁，怎么注册不了账号，登录不进去阿。急急急！！！！！！

**Comment by hoojking** [comment]
你好 ，最近几天在b站上看了些关于java的内容 但是我自己运行的时候依然有很大问题



实在不知道是哪里的错误，如果您有时间的话，能否演示下你的运行过程。
希望不会打扰你，期待你的回复！！！
